### PR TITLE
Suggested changes

### PR DESCRIPTION
**Pull request by chouseknecht**
Alexey- 

This PR adds the following changes: 

- Fixes build.sh/build.yml
- Adds *Post Install* steps to README
- Adds dumb-init
- Adds APACHE_ASSET_PATHS
- Moves *site* to *files*
- Adds *command* directive to container.yml

### CODE REVIEW

**Comment by awasilyev** [comment]
Generally make sense. Thanks for fixing typos and gramma mistakes.
What is the reason of adding dumb-init and moving entrypoint script to the /usr/bin?

**Comment by chouseknecht** [comment]
`dumb-init` makes stopping/killing the container work faster more reliably, because it knows how to handle signals sent to PID 1. It's not strictly required, but a good 'best practice'.

Moving entrypoint.sh to /usr/bin is a style thing. I think having it in a path that's part of PATH, is a good practice, and it's consistent with the other roles we've published so far.

I'm trying to figure out why tests are failing...

**Comment by chouseknecht** [comment]
@wasilyev, test are actually passing in my repo: https://travis-ci.org/chouseknecht/apache-container/builds/188677108

The issue appears to be "ansible-container install git+https://github.com/${TRAVIS_REPO_SLUG},${TRAVIS_COMMIT}" fails because this is a PR, and those vars don't account for a PR. I don't see a see an obvious way to fix this.

Since tests are passing for my repo, I think if you merge the PR, tests will work in your repo. It's the *transitive* property of tests. :-)

**Comment by awasilyev** [comment]
I checked popular official docker hub images - non of them uses dumb-init and store entrypoint in /.
But yes, it is style-only things - if you prefer this style - ok, lets do it in this way.

**Pull request merged**
